using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.CSharp.Transforms;
using ICSharpCode.Decompiler.Semantics;
using ICSharpCode.Decompiler.TypeSystem;

namespace GodotMonoDecomp;

/// <summary>
/// Restores source-level shape for methods generated by the Regex source generator.
/// </summary>
public class RestoreGeneratedRegexMethods : DepthFirstAstVisitor, IAstTransform
{
	private const string GeneratedRegexAttributeFullName = "System.Text.RegularExpressions.GeneratedRegexAttribute";
	private const string GeneratedCodeAttributeFullName = "System.CodeDom.Compiler.GeneratedCodeAttribute";
	private const string RegexGeneratorName = "System.Text.RegularExpressions.Generator";

	public void Run(AstNode rootNode, TransformContext context)
	{
		rootNode.AcceptVisitor(this);
	}

	public override void VisitMethodDeclaration(MethodDeclaration methodDeclaration)
	{
		if (!HasGeneratedRegexAttribute(methodDeclaration))
		{
			base.VisitMethodDeclaration(methodDeclaration);
			return;
		}

		bool hasRegexGeneratorGeneratedCode = RemoveRegexGeneratorGeneratedCodeAttributes(methodDeclaration);
		bool hasGeneratedBodyPattern = HasGeneratedRegexBodyPattern(methodDeclaration);
		if (!hasGeneratedBodyPattern && !hasRegexGeneratorGeneratedCode)
		{
			base.VisitMethodDeclaration(methodDeclaration);
			return;
		}

		methodDeclaration.Modifiers |= Modifiers.Partial;
		methodDeclaration.Body = null;
		if (methodDeclaration.Parent is TypeDeclaration containingType)
		{
			containingType.Modifiers |= Modifiers.Partial;
		}
	}

	private static bool HasGeneratedRegexAttribute(MethodDeclaration methodDeclaration)
	{
		foreach (var section in methodDeclaration.Attributes)
		{
			foreach (var attribute in section.Attributes)
			{
				if (IsAttribute(attribute, GeneratedRegexAttributeFullName, "GeneratedRegex"))
				{
					return true;
				}
			}
		}

		return false;
	}

	private static bool RemoveRegexGeneratorGeneratedCodeAttributes(MethodDeclaration methodDeclaration)
	{
		bool removedAny = false;
		foreach (var section in methodDeclaration.Attributes.ToArray())
		{
			foreach (var attribute in section.Attributes.ToArray())
			{
				if (IsRegexGeneratorGeneratedCodeAttribute(attribute))
				{
					attribute.Remove();
					removedAny = true;
				}
			}

			if (section.Attributes.Count == 0)
			{
				section.Remove();
			}
		}

		return removedAny;
	}

	private static bool IsRegexGeneratorGeneratedCodeAttribute(ICSharpCode.Decompiler.CSharp.Syntax.Attribute attribute)
	{
		if (!IsAttribute(attribute, GeneratedCodeAttributeFullName, "GeneratedCode"))
		{
			return false;
		}

		if (attribute.Arguments.FirstOrDefault() is PrimitiveExpression { Value: string toolName })
		{
			return toolName == RegexGeneratorName;
		}

		return false;
	}

	private static bool HasGeneratedRegexBodyPattern(MethodDeclaration methodDeclaration)
	{
		if (methodDeclaration.Body is not { Statements.Count: 1 })
		{
			return false;
		}

		if (methodDeclaration.Body.Statements.First() is not ReturnStatement returnStatement)
		{
			return false;
		}

		if (returnStatement.Expression is not MemberReferenceExpression memberReference)
		{
			return false;
		}

		if (!string.Equals(memberReference.MemberName, "Instance", StringComparison.Ordinal))
		{
			return false;
		}

		string targetText = memberReference.Target.ToString();
		return targetText.Contains("RegexGenerator", StringComparison.Ordinal)
			|| targetText.Contains("_003CRegexGenerator", StringComparison.Ordinal);
	}

	private static bool IsAttribute(ICSharpCode.Decompiler.CSharp.Syntax.Attribute attribute, string expectedFullName, string expectedShortName)
	{
		if (attribute.Type.Annotation<TypeResolveResult>() is { Type: { } typeResult })
		{
			if (string.Equals(typeResult.FullName, expectedFullName, StringComparison.Ordinal))
			{
				return true;
			}
		}

		if (attribute.GetSymbol() is IMethod method && method.DeclaringType != null)
		{
			if (string.Equals(method.DeclaringType.FullName, expectedFullName, StringComparison.Ordinal))
			{
				return true;
			}
		}

		return HasMatchingShortAttributeName(attribute.Type.ToString(), expectedShortName);
	}

	private static bool HasMatchingShortAttributeName(string typeName, string expectedShortName)
	{
		if (typeName.StartsWith("global::", StringComparison.Ordinal))
		{
			typeName = typeName.Substring("global::".Length);
		}

		int lastDot = typeName.LastIndexOf('.');
		if (lastDot >= 0 && lastDot < typeName.Length - 1)
		{
			typeName = typeName.Substring(lastDot + 1);
		}

		if (typeName.EndsWith("Attribute", StringComparison.Ordinal))
		{
			typeName = typeName.Substring(0, typeName.Length - "Attribute".Length);
		}

		return string.Equals(typeName, expectedShortName, StringComparison.Ordinal);
	}
}
